### ISSUE TITLE
Monturas lvl 40 Paladin/brujo y flight form

### ISSUE THREAD

**Issue by GastonCK** [arielcami/AutoSkills_3.3.5a#1]
Hola recien estuve probando tu script y la verdad que esta fantastico! lo estamos probando para ver si lo ponemos en el server (Andes) Te queria hacer una consulta ya que tambien vi el video y algo no me esta funcionando como en tu video: no me esta enseñando las monturas de lvl 40 del paladin y de brujo, las de lvl 20 si.
Probé con equitación en TRUE y en FALSE pero no enseña lo spells de esas monturas como en el video que subiste.
Tampoco me enseña las formas voladoras del druida.
![image](https://github.com/arielcami/AutoLearn_3.3.5a/assets/65800273/3a3454f2-4aea-4d79-aa7a-a27ac7dd5628)

**Comment by arielcami** [comment]
Entiendo que inicialmente estuvo como dices, en el video de explicación.
Pero luego en un test más detallado, vi que el comportamiento original no es así.

Brujos y Paladines aprenden la montura desde su entrenador al nivel 20 sin problemas, pero al 40 no.
Para poder hacerlo deben comprar la habilidad en jinete. Entonces si el objetivo del script es enseñar
lo mismo que enseña el trainer, este comportamiento había que arreglarlo.

Gracias por el issue, y me parece perfecto que quieran utilizarlo en Andes, más bien les insto a hacerlo!
